name: "ZOAU Node.js Module Bug report"
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.

        This issue tracker is for bugs and issues found within the zoau Node.js module.

        Please fill in as much of the form below as you're able.
  - type: input
    attributes:
      label: zoau Node.js module version
      description: |
        version of zoau Node.js module installed
  - type: input
    attributes:
      label: Node.js Version
      description: Output of `node -v`
  - type: input
    attributes:
      label: ZOAU version
      description: |
        output of `zoaversion`
  - type: input
    attributes:
      label: Platform Information
      description: |
        output of `uname -a`
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: Enter details about your bug, preferably a simple code snippet.
  - type: textarea
    attributes:
      label: How often does it reproduce? Is there a required condition?
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible please provide textual output instead of screenshots.
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible please provide textual output instead of screenshots.
  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.
